version: "3.7"

services: 
  express:
    build: 
      args: 
        NODE_ENV: development
    command: npm run start:dev --workspace express-server
    environment: 
      - NODE_ENV='development'
    volumes:
      - ./services:/app/services